require:
  - rubocop-rails
Rails:
  Enabled: true
Layout/LineLength:
  Max: 100
Rails/TimeZone:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/RescueStandardError:
  Enabled: false
Style/RescueModifier:
  Enabled: false

