# Add configuration values here, as shown below.

aws_access_key_id: xxxx
aws_secret_access_key: xxxx
aws_region: eu-west-1

smtp_address: 'smtp.gmail.com'
smtp_port: '587'
smtp_domain: 'xxxx'
smtp_username: 'xxxx@gmail.com'
smtp_password: 'xxxx'
smtp_authentication: 'plain'
smtp_starttls: 'true'
smtp_ssl_verify: 'none'
smtp_ssl: ''

development:
  db_host: localhost
  db_username: postgres
  db_password: postgres
  db_name: xxxx-development
  s3_bucket: xxxx-development
  backend_host: localhost:3000
  backend_protocol: http
  frontend_host: localhost:3000
  frontend_protocol: http

test:
  db_host: localhost
  db_username: jenkins
  db_password: jenkins
  db_name: xxxx-test
  s3_bucket: xxxx-test
  backend_host: localhost:3000
  backend_protocol: http
  frontend_host: localhost:3000
  frontend_protocol: http

staging:
  db_host: localhost
  db_username: postgres
  db_password: xxxxxxxxxxx
  db_name: xxxx-staging
  s3_bucket: xxxx-staging
  backend_host: localhost:3000
  backend_protocol: http
  frontend_host: localhost:3000
  frontend_protocol: http

production:
  secret_key_base: 1a26fee9e7c1c50624e29510e89dbe68f01d71f248ee44660ba11f0f97100a450e971a1b092fe84e85135b2074684753d2cf461a8e8ee506cd80f2bc8865d987
  db_host: localhost
  db_username: postgres
  db_password: xxxxxxxxxxx
  db_name: xxxx-production
  s3_bucket: "xxxx-production"
  backend_host: localhost:3000
  backend_protocol: http
  frontend_host: localhost:3000
  frontend_protocol: http
