# Just an EXAMPLE of credentials config. Set the actual credentials with:
#      EDITOR=vim rails credentials:edit
#
# More info: https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336


# Common credentials
secret_key_base: 92f2023443fb85257ef490d9cc4ab6ac7da514e724cbce7813ab1df1e3edc50b8d77e125793b147c660a70904be09a7bbd064a08033db9cf97ed31cae6b738c6

# Environment-specific credentials
development:

test:

staging:

production:
  db:
    name:
    host:
    username:
    password:
  aws:
    access_key_id:
    secret_access_key:
    region:
    s3_bucket:
  url:
    backend:
      host:
      protocol:
    frontend:
      host:
      protocol:
  smtp:
    address: smtp.gmail.com
    port: 587
    domain: moku.io
    username: support@moku.io
    password:
    authentication: plain
    starttls: true
    ssl_verify: none
    ssl: # Notice: keep it empty for Gmail.
